// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKUdrA8mnb2BJrP8Dy0GFBp02K0oLIYHE',
    appId: '1:710033610290:web:9ebd3a96ce92645f374e2b',
    messagingSenderId: '710033610290',
    projectId: 'flutter-calendar-785db',
    authDomain: 'flutter-calendar-785db.firebaseapp.com',
    storageBucket: 'flutter-calendar-785db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl9k4I9hpNFLf4802kftOEqMd9clsOCEo',
    appId: '1:710033610290:android:b1342c4659d2d646374e2b',
    messagingSenderId: '710033610290',
    projectId: 'flutter-calendar-785db',
    storageBucket: 'flutter-calendar-785db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXrT9RL5E6Bap7x4RRwOnU4u2ZqzoZ5U',
    appId: '1:710033610290:ios:dff30f42789701b5374e2b',
    messagingSenderId: '710033610290',
    projectId: 'flutter-calendar-785db',
    storageBucket: 'flutter-calendar-785db.appspot.com',
    iosClientId: '710033610290-ej3b13c4m94gbmpba8ahs9islr0qacnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar',
  );
}
